version: "2"
services:
  api:
    build: .
    volumes:
     - ~/boletodb/upMongo:/home/upMongo     
     - ~/boleto_cert:/home/mundipagg/boleto_cert
    ports:
     - "#{CONF_EXPOSEPORT}#:3000"
    environment:
     - API_PORT=#{CONF_APIPORT}#
     - API_VERSION=#{CONF_API_VERSION}#
     - PDF_API=#{CONF_PDF_API}#
     - ENVIRONMENT=#{CONF_ENVIRONMENT}#
     - SEQ_URL=#{CONF_SEQ_URL}#
     - SEQ_API_KEY=#{CONF_SEQ_API_KEY}#
     - ENABLE_REQUEST_LOG=#{CONF_ENABLE_REQUEST_LOG}#
     - ENABLE_PRINT_REQUEST=#{CONF_ENABLE_PRINT_REQUEST}#
     - URL_BB_REGISTER_BOLETO=#{CONF_URL_BB_REGISTER_BOLETO}#
     - URL_BB_TOKEN=#{CONF_URL_BB_TOKEN}#
     - MONGODB_URL=#{CONF_MONGODB_URL}#
     - MONGODB_USER=#{CONF_MONGODB_USER}#
     - MONGODB_PASSWORD=#{CONF_MONGODB_PASSWORD}#
     - INFLUXDB_HOST=#{CONF_INFLUXDB_HOST}#
     - INFLUXDB_PORT=#{CONF_INFLUXDB_PORT}#
     - APP_URL=#{CONF_APP_URL}#
     - BOLETO_JSON_STORE=#{CONF_BOLETO_JSON_STORE}#
     - CERT_BOLETO_CRT=#{CONF_CERT_BOLETO_CRT}#
     - CERT_BOLETO_KEY=#{CONF_CERT_BOLETO_KEY}#
     - CERT_BOLETO_CA=#{CONF_CERT_BOLETO_CA}#
     - URL_CAIXA=#{CONF_URL_CAIXA}#
     - URL_CITI=#{CONF_URL_CITI}#
     - URL_CITI_BOLETO=#{CONF_URL_CITI_BOLETO}#
     - URL_SANTANDER_TICKET=#{CONF_URL_SANTANDER_TICKET}#
     - URL_SANTANDER_REGISTER=#{CONF_URL_SANTANDER_REGISTER}#
     - URL_BRADESCO=#{CONF_URL_BRADESCO}#
  pdfapi:
    image: pmoneda/pdfapi:latest
    container_name: "pdfapi"
    ports:
        - 8089:8080    
  