version: "2"
services:
  api:
    build: .
    volumes:
     - ~/boletodb/upMongo:/home/upMongo
     - ~/boleto_ssh:/home/mundipagg/boleto_ssh
    ports:
     - "8080:3000"
    environment:
     - API_PORT=3000
     - API_VERSION=0.0.1
     - ENVIRONMENT=Development
     - SEQ_URL=http://example.mundipagg.com
     - SEQ_API_KEY=xxxxxxxxxxxxx
     - ENABLE_REQUEST_LOG=false
     - ENABLE_PRINT_REQUEST=true
     - URL_BB_REGISTER_BOLETO=https://cobranca.desenv.bb.com.br:7101/registrarBoleto
     - URL_BB_TOKEN=https://oauth.desenv.bb.com.br:43000/oauth/token
     - MONGODB_URL=10.0.2.15:27017
     - APP_URL=http://localhost:8080/boleto
     - BOLETO_JSON_STORE=/home/upMongo
     - URL_CAIXA=https://des.barramento.caixa.gov.br/sibar/ManutencaoCobrancaBancaria/Boleto/Externo
     - URL_CITI=https://citigroupsoa.citigroup.com/comercioeletronico/registerboleto/RegisterBoletoSOAP
     - TLS_CERT_PATH=/home/mundipagg/boleto_ssh/cert.pem
     - TLS_KEY_PATH=/home/mundipagg/boleto_ssh/key.pem
  mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ~/boletodb/db:/data/db
          - ~/boletodb/configdb:/data/configdb
          - ~/dump_boletodb:/dump/boletoapi
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null
